services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - app_network

  producer:
    build:
      context: producer
    container_name: 'producer'
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - '8000:8000'
    networks:
      - app_network

  worker_add:
    container_name: worker_add
    build:
      context: worker-add
    stop_signal: SIGINT
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

  worker_div:
    container_name: worker_div
    build:
      context: worker-div
    stop_signal: SIGINT
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

  worker_mul:
    container_name: worker_mul
    build:
      context: worker-mul
    stop_signal: SIGINT
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

  worker_sub:
    build:
      context: worker_sub
    container_name: 'worker_sub'
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

  worker_logs:
    build:
      context: worker_logs
    container_name: 'worker_logs'
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - '4000:4000' 
    networks:
      - app_network

volumes:
  postgres-db:
  rabbitmq-data:
  rabbitmq-log:

networks:
  app_network: